=== Julendev04/ENPRESAKO-FORMAKUNTZAREN-PROIEKTUA_Mikel_Julen/dtd/cv_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Curriculum_Vitae (datuPertsonalak, formakuntza, Lan-experientzia, gaitasunak)>
<!ELEMENT datuPertsonalak (izena, abizena, korreoa, telefonoa)>
<!ELEMENT izena (#PCDATA)>
<!ELEMENT abizena (#PCDATA)>
<!ELEMENT korreoa (#PCDATA)>
<!ELEMENT telefonoa (#PCDATA)>

<!ELEMENT formakuntza (ikasketak+)>
<!ELEMENT ikasketak (titulua, zentroa, urtea)>
<!ELEMENT titulua (#PCDATA)>
<!ELEMENT zentroa (#PCDATA)>
<!ELEMENT urtea (#PCDATA)>
<!ATTLIST ikasketak
    kodea ID #REQUIRED
    mota (gradua | masterra | ziurtagiria | bestelakoa) "bestelakoa"
>
<!ELEMENT Lan-experientzia (lana+)>
<!ELEMENT lana (postua, enpresa, lan-iraupena)>
<!ELEMENT postua (#PCDATA)>
<!ELEMENT enpresa (#PCDATA)>
<!ELEMENT lan-iraupena (#PCDATA)>
<!ATTLIST lana
    mota (praktikak | kontratua | autonomoa | freelance) #REQUIRED
    erlazionatutakoIkasketa IDREF #IMPLIED
>
<!ELEMENT gaitasunak (gaitasuna+)>
<!ELEMENT gaitasuna (#PCDATA)>
<!ATTLIST gaitasuna
    maila (oinarrizkoa | ertaina | aurreratua | aditua) "ertaina"
    mota (softwarea | programazioa | diseinua | bestelakoa) #REQUIRED
>

=== Julendev04/ENPRESAKO-FORMAKUNTZAREN-PROIEKTUA_Mikel_Julen/dtd/cv_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Curriculum_Vitae SYSTEM "cv_dtd.dtd">
<Curriculum_Vitae>
    <datuPertsonalak>
        <izena></izena>
        <abizena></abizena>
        <korreoa></korreoa>
        <telefonoa></telefonoa>
    </datuPertsonalak>
    
    <formakuntza>
        <ikasketak>
            <titulua></titulua>
            <zentroa></zentroa>
            <urtea></urtea>
        </ikasketak>
    </formakuntza>
    
    <Lan-experientzia>
        <lana>
            <postua></postua>
            <enpresa></enpresa>
            <lan-iraupena></lan-iraupena>
        </lana>
    </Lan-experientzia>
    
    <gaitasunak>
        <gaitasuna></gaitasuna>
        <gaitasuna></gaitasuna>
        <gaitasuna></gaitasuna>
    </gaitasunak>
</Curriculum_Vitae>
